version: "3.9"

networks:
  amazon-clone:
    external: false

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "9090:9090"
    networks:
      - amazon-clone

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - amazon-clone

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    networks:
      - amazon-clone

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yml"]
    volumes:
      - ./monitoring/tempo.yml:/etc/tempo.yml
    ports:
      - "3200:3200"
    networks:
      - amazon-clone

  loki:
    image: grafana/loki:latest
    command: ["-config.file=/etc/loki/loki-config.yml"]
    volumes:
      - ./logging/loki-config.yml:/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    networks:
      - amazon-clone

  promtail:
    image: grafana/promtail:latest
    command: ["-config.file=/etc/promtail/promtail-config.yml"]
    volumes:
      - ./logging/promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - amazon-clone
