apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-chart.name" . }}
spec:
  selector:
    app: {{ include "service-chart.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
