apiVersion: v1
kind: Service
metadata:
  name: rating-service
  labels:
    app: rating-service
spec:
  selector:
    app: rating-service
  ports:
    - port: 80
      targetPort: 8011
      protocol: TCP
  type: ClusterIP
