apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service
  namespace: argocd
spec:
  project: amazon-clone
  source:
    repoURL: https://github.com/kalyan0996/Amazon-Clone.git
    targetRevision: main
    path: backend/order-service/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: amazon-clone
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
