apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
spec:
  project: amazon-clone
  source:
    repoURL: https://example.com/amazon-clone.git
    targetRevision: main
    path: backend/user-service/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: amazon-clone
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
