apiVersion: v1
kind: PersistentVolume
metadata:
  name: amazon-clone-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: amazon-clone-standard
  hostPath:
    path: /data/amazon-clone
