apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amazon-clone-pvc
  namespace: amazon-clone
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: amazon-clone-standard
  resources:
    requests:
      storage: 10Gi
