apiVersion: v1
kind: Service
metadata:
  name: admin-service
  labels:
    app: admin-service
spec:
  selector:
    app: admin-service
  ports:
    - port: 80
      targetPort: 8019
      protocol: TCP
  type: ClusterIP
