nameOverride: ""
replicaCount: 2

image:
  repository: amazon-clone/CHANGEME
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  host: CHANGEME.amazon-clone.local

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

env: {}
